'use client'

import Link from 'next/link'
import { ArrowUpRight, Clock3, ScrollText } from 'lucide-react'
import { formatDate } from '@/lib/utils'

type AuditLog = { id: string; userName?: string; actionPerformed?: string; targetResource?: string; createdAt?: string }

export function AuditLogCard({ logs }: { logs: AuditLog[] }) {
  return <section className="relative overflow-hidden rounded-2xl border border-white bg-white/90 p-5 shadow-[0_10px_30px_rgba(15,23,42,.07)] backdrop-blur"><div className="absolute right-0 top-0 h-20 w-20 rounded-bl-[3rem] bg-violet-50" /><div className="relative mb-5 flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-500 text-white shadow-lg shadow-violet-500/20"><ScrollText className="h-5 w-5" /></span><div><h3 className="text-sm font-black text-slate-950">Workspace activity</h3><p className="text-xs text-slate-500">Audited administrative actions</p></div></div><Link href="/admin/audit" className="text-xs font-bold text-violet-700"><ArrowUpRight className="h-4 w-4" /></Link></div>{logs.length === 0 ? <p className="rounded-xl border border-dashed border-slate-200 py-7 text-center text-xs text-slate-500">Activity will be recorded here as the workspace is configured.</p> : <div className="space-y-3">{logs.slice(0, 4).map(log => <div key={log.id} className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-violet-100 bg-violet-50 text-[10px] font-black text-violet-700">{log.userName?.split(' ').map(name => name[0]).join('').slice(0, 2) || 'SY'}</span><div className="min-w-0 flex-1"><p className="truncate text-xs text-slate-700"><strong>{log.userName || 'System'}</strong> <span className="text-slate-500">{log.actionPerformed?.replace(/_/g, ' ') || 'performed an action'}</span></p><p className="mt-0.5 truncate text-[10px] font-medium text-slate-500">{log.targetResource || 'Workspace'}</p></div><span className="flex shrink-0 items-center gap-1 text-[10px] text-slate-400"><Clock3 className="h-3 w-3" />{log.createdAt ? formatDate(log.createdAt, 'relative') : ''}</span></div>)}</div>}</section>
}
